# Generated by Django 3.2.3 on 2021-06-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0002_auto_20210619_2233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='type',
            new_name='types',
        ),
    ]
