# Generated by Django 3.2.3 on 2021-06-19 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0003_rename_type_vehicle_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='types',
        ),
    ]
