# Generated by Django 3.2.3 on 2021-06-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0004_remove_vehicle_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='types',
            field=models.CharField(default='Other', max_length=10),
            preserve_default=False,
        ),
    ]
