# Generated by Django 3.2.3 on 2021-06-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0006_rename_records_sales_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='company',
            field=models.CharField(max_length=128),
        ),
    ]
